### ISSUE TITLE
Heroku & merging branch with master

### ISSUE THREAD

**Issue by arissafram** [arissafram/full-crud-project#4]
Deploying my app to Heroku seemingly worked, but I'm unable to actually open the app. Is this because I pushed a branch, rather than the master?

Similarly, I've been working in a branch and am hesitant to merge it back with the master because I don't fully understand what happens in a merge - will it override that version, or add them together?

Could you take a look with me in the morning?

murmuring-earth-83372.herokuapp.com

**Comment by JohnrBell** [comment]
pushing the branch should be no issue. you can also go into your main folder and "rm -rf .git" to disconnect it from github, then re-init in a new repo if you want. 

also, check heroku logs to see whats up. 

either way, i'll take a look before you present.

**Comment by arissafram** [comment]
@JohnrBell thanks! i was able to work it out this morning. I'll close this now.
